spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_app
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true


  flyway:
    enabled: true

  springdoc:
    api-docs:
      path: /api/api-docs
    swagger-ui:
      path: /swagger/index.html
